//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSeriesService.Client.TimeSeriesReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IrregularTimeSeries", Namespace="http://schemas.datacontract.org/2004/07/TimeSeries")]
    [System.SerializableAttribute()]
    public partial class IrregularTimeSeries : TimeSeries.TimeSeriesBase, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetPointTimeSeries", Namespace="http://schemas.datacontract.org/2004/07/TimeSeries")]
    [System.SerializableAttribute()]
    public partial class SetPointTimeSeries : TimeSeries.TimeSeriesBase, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegularTimeSeries", Namespace="http://schemas.datacontract.org/2004/07/TimeSeries")]
    [System.SerializableAttribute()]
    public partial class RegularTimeSeries : TimeSeries.TimeSeriesBase, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cjl-magistri.com", ConfigurationName="TimeSeriesReference.ITimeSeriesService")]
    public interface ITimeSeriesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cjl-magistri.com/ITimeSeriesService/New", ReplyAction="http://www.cjl-magistri.com/ITimeSeriesService/NewResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TimeSeriesService.Client.TimeSeriesReference.IrregularTimeSeries))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TimeSeriesService.Client.TimeSeriesReference.SetPointTimeSeries))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TimeSeriesService.Client.TimeSeriesReference.RegularTimeSeries))]
        TimeSeries.TimeSeriesBase New(TimeSeries.DataPoint[] dataPoints);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cjl-magistri.com/ITimeSeriesService/New", ReplyAction="http://www.cjl-magistri.com/ITimeSeriesService/NewResponse")]
        System.Threading.Tasks.Task<TimeSeries.TimeSeriesBase> NewAsync(TimeSeries.DataPoint[] dataPoints);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeSeriesServiceChannel : TimeSeriesService.Client.TimeSeriesReference.ITimeSeriesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeSeriesServiceClient : System.ServiceModel.ClientBase<TimeSeriesService.Client.TimeSeriesReference.ITimeSeriesService>, TimeSeriesService.Client.TimeSeriesReference.ITimeSeriesService {
        
        public TimeSeriesServiceClient() {
        }
        
        public TimeSeriesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeSeriesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeSeriesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeSeriesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TimeSeries.TimeSeriesBase New(TimeSeries.DataPoint[] dataPoints) {
            return base.Channel.New(dataPoints);
        }
        
        public System.Threading.Tasks.Task<TimeSeries.TimeSeriesBase> NewAsync(TimeSeries.DataPoint[] dataPoints) {
            return base.Channel.NewAsync(dataPoints);
        }
    }
}
